"""Initial migration

Revision ID: d9014c137640
Revises: 
Create Date: 2025-03-31 00:04:51.498144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9014c137640'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('short_url', sa.String(), nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expire_at', sa.DateTime(), nullable=False),
    sa.Column('link_owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['link_owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_link_owner_id'), 'links', ['link_owner_id'], unique=False)
    op.create_index(op.f('ix_links_short_url'), 'links', ['short_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_short_url'), table_name='links')
    op.drop_index(op.f('ix_links_link_owner_id'), table_name='links')
    op.drop_table('links')
    # ### end Alembic commands ###
